// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB-oRJbZo_qM2a1kHGzhSrnMQMZh665z4',
    appId: '1:482456100266:web:858278565f42a4b6b19fd3',
    messagingSenderId: '482456100266',
    projectId: 'queueless-office',
    authDomain: 'queueless-office.firebaseapp.com',
    storageBucket: 'queueless-office.firebasestorage.app',
    measurementId: 'G-6SCWL1S52B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-neiwASjDNbXYDGEHJ4WE5WPN9UEjei8',
    appId: '1:482456100266:android:2fea4ea9dc811cdbb19fd3',
    messagingSenderId: '482456100266',
    projectId: 'queueless-office',
    storageBucket: 'queueless-office.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEPJPyInGVMdbZKjb_oTtSHbNro9jLUU0',
    appId: '1:482456100266:ios:2a6e1518fc691f28b19fd3',
    messagingSenderId: '482456100266',
    projectId: 'queueless-office',
    storageBucket: 'queueless-office.firebasestorage.app',
    iosBundleId: 'com.example.queuelessOffice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEPJPyInGVMdbZKjb_oTtSHbNro9jLUU0',
    appId: '1:482456100266:ios:2a6e1518fc691f28b19fd3',
    messagingSenderId: '482456100266',
    projectId: 'queueless-office',
    storageBucket: 'queueless-office.firebasestorage.app',
    iosBundleId: 'com.example.queuelessOffice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB-oRJbZo_qM2a1kHGzhSrnMQMZh665z4',
    appId: '1:482456100266:web:592a66fa94d35838b19fd3',
    messagingSenderId: '482456100266',
    projectId: 'queueless-office',
    authDomain: 'queueless-office.firebaseapp.com',
    storageBucket: 'queueless-office.firebasestorage.app',
    measurementId: 'G-C1DV8K8Y08',
  );
}
