server.port=8081
spring.application.name=api-gateway

services.auth.url=http://localhost:8082
services.office.url=http://localhost:8083
services.customer.url=http://localhost:8084

spring.servlet.multipart.enabled=false
