// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvlVTx5oipYdZK-JhgYbuZDmi07wkd_W4',
    appId: '1:1048114398072:web:37aa20a0da0ef9cca87e8d',
    messagingSenderId: '1048114398072',
    projectId: 'queueless-2cbfd',
    authDomain: 'queueless-2cbfd.firebaseapp.com',
    storageBucket: 'queueless-2cbfd.firebasestorage.app',
    measurementId: 'G-PMQLXN88J0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCoMuDSeS1OuVwFRguixf19EcN25eVI7Y',
    appId: '1:1048114398072:android:7df228b3e7656954a87e8d',
    messagingSenderId: '1048114398072',
    projectId: 'queueless-2cbfd',
    storageBucket: 'queueless-2cbfd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLb9vq5VCLRPRaGsC-1W4vMRG6692JipI',
    appId: '1:1048114398072:ios:db55c40170828d4fa87e8d',
    messagingSenderId: '1048114398072',
    projectId: 'queueless-2cbfd',
    storageBucket: 'queueless-2cbfd.firebasestorage.app',
    iosClientId: '1048114398072-ih5cnqlhge7kr6ik1e5uk37cnt26u5bj.apps.googleusercontent.com',
    iosBundleId: 'com.example.queueless',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLb9vq5VCLRPRaGsC-1W4vMRG6692JipI',
    appId: '1:1048114398072:ios:db55c40170828d4fa87e8d',
    messagingSenderId: '1048114398072',
    projectId: 'queueless-2cbfd',
    storageBucket: 'queueless-2cbfd.firebasestorage.app',
    iosClientId: '1048114398072-ih5cnqlhge7kr6ik1e5uk37cnt26u5bj.apps.googleusercontent.com',
    iosBundleId: 'com.example.queueless',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvlVTx5oipYdZK-JhgYbuZDmi07wkd_W4',
    appId: '1:1048114398072:web:744a7ad999d52b52a87e8d',
    messagingSenderId: '1048114398072',
    projectId: 'queueless-2cbfd',
    authDomain: 'queueless-2cbfd.firebaseapp.com',
    storageBucket: 'queueless-2cbfd.firebasestorage.app',
    measurementId: 'G-CJM7CX8NEZ',
  );
}
